-- SQL continues
-- Task 6
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.unique_id (id INT AUTO_INCREMENT PRIMARY KEY NOT NULL UNIQUE, name VARCHAR(256) NOT NULL);
